# Generated by Django 3.0.3 on 2020-05-03 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20200503_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCharacters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='app01.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Authers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('books', models.ManyToManyField(related_name='authers', to='app01.Book')),
            ],
        ),
    ]
