# Generated by Django 3.0.3 on 2020-04-26 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flat',
            unique_together={('building', 'no')},
        ),
    ]
